name: biencoder-trained

data:
  data_path: data/processed
  corpus_path: data/raw/updated_corpus.csv

retrieval:
  method: dense
  top_k: 100
  params:
    model_name: phatvucoder/vietnamese-bi-encoder
    segmentation: pyvi

reranking: null

evaluation:
  metrics:
    - { name: mrr@10, fn: mrr_at_k, k: 10 }
    - { name: success@10, fn: success_at_k, k: 10 }
    - { name: recall@100, fn: recall_at_k, k: 100 }

output:
  predictions: results/biencoder_trained/outputeval.txt
  scores: results/biencoder_trained/scores.json
