name: zero-shot-harrier-oss-v1-270m

data:
  data_path: data/processed
  corpus_from: eval

retrieval:
  method: dense
  top_k: 100
  params:
    model_name: microsoft/harrier-oss-v1-270m
    encode_kwargs: { batch_size: 64 }
    max_length: 512

reranking: null

evaluation:
  metrics:
    all

output:
  predictions: results/model-selection/harrier-oss-v1-270m/outputeval.txt
  scores: results/model-selection/harrier-oss-v1-270m/scores.json
