name: zero-shot-vietnamese-bi-encoder

data:
  data_path: data/processed
  corpus_from: eval

retrieval:
  method: dense
  top_k: 100
  params:
    model_name: bkai-foundation-models/vietnamese-bi-encoder
    segmentation: pyvi
    encode_kwargs: { batch_size: 256 }
    max_length: 256

reranking: null

evaluation:
  metrics:
    all

output:
  predictions: results/model-selection/vietnamese-bi-encoder/outputeval.txt
  scores: results/model-selection/vietnamese-bi-encoder/scores.json
